INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (1, 'Co oznacza skrót HTML?', 'HyperText Markup Language', 'HyperText Make Language', 'HighText Mark Language', 'HyperLink Text Language');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (1, 'Który symbol służy do przypisania wartości zmiennej?', '=', '==', ':', '#');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (1, 'Jaki jest wynik działania 2 + 2 * 2?', '6', '8', '4', '10');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (1, 'Co to jest "bit"?', 'Najmniejsza jednostka informacji (0 lub 1)', 'Znak w kodzie ASCII', 'Rodzaj procesora', 'Błąd w programie');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (1, 'Które rozszerzenie pliku wskazuje na skrypt Pythona?', '.py', '.txt', '.exe', '.java');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (1, 'Co robi skrót klawiszowy Ctrl+C?', 'Kopiuje', 'Wkleja', 'Wycina', 'Zapisuje');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (2, 'Jaki jest wynik logiczny: PRAWDA i FAŁSZ?', 'FAŁSZ', 'PRAWDA', 'NIE WIEM', 'NULL');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (2, 'Co oznacza skrót CPU?', 'Central Processing Unit', 'Central Program Utility', 'Computer Personal Unit', 'Core Processing Unit');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (2, 'Jak nazywa się błąd w programie komputerowym?', 'Bug', 'Feature', 'Virus', 'Spam');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (2, 'W systemie binarnym, liczba 10 to w systemie dziesiętnym:', '2', '10', '3', '5');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (2, 'Jaki jest wynik 10 % 3 (modulo)?', '1', '3', '0', '3.33');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (2, 'Co oznacza CSS?', 'Cascading Style Sheets', 'Computer Style Sheets', 'Creative Style System', 'Colorful Style Sheets');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (2, 'Co robi "garbage in, garbage out"?', 'Błędne dane wejściowe dają błędne wyniki', 'Śmieci w kodzie to błędy', 'Kosza nie należy opróżniać', 'Błędy są ignorowane');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (3, 'Która pętla wykonuje się przynajmniej raz?', 'Do-While', 'While', 'For', 'Foreach');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (3, 'Co przechowuje typ zmiennej "String"?', 'Ciąg znaków', 'Liczby całkowite', 'Wartości logiczne', 'Liczby zmiennoprzecinkowe');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (3, 'Indeksowanie tablic w większości języków zaczyna się od:', '0', '1', '-1', '2');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (3, 'Instrukcja warunkowa to:', 'If', 'Loop', 'Var', 'Class');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (3, 'Co oznacza "null"?', 'Brak wartości / Pusty wskaźnik', 'Zero', 'Pusta tablica', 'Błąd krytyczny');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (3, 'Kto stworzył system Linux?', 'Linus Torvalds', 'Bill Gates', 'Steve Jobs', 'Ada Lovelace');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (3, 'Interpreter przetwarza kod:', 'Linia po linii w trakcie działania', 'Kompiluje całość przed uruchomieniem', 'Tylko w chmurze', 'Tylko błędy');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (3, 'Który status HTTP oznacza "Not Found"?', '404', '200', '500', '301');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (4, 'Funkcja, która wywołuje samą siebie to funkcja:', 'Rekurencyjna', 'Iteracyjna', 'Statyczna', 'Liniowa');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (4, 'Operator "==" służy do:', 'Porównania wartości', 'Przypisania wartości', 'Negacji', 'Koniunkcji');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (4, 'Co oznacza skrót IDE?', 'Integrated Development Environment', 'Internal Data Engine', 'Internet Development Environment', 'Integrated Design Editor');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (4, 'W SQL, aby pobrać wszystkie dane z tabeli, użyjesz:', 'SELECT *', 'GET ALL', 'FETCH *', 'SHOW ALL');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (4, 'Komentarz w języku Python zaczyna się od:', '#', '//', '/*', '--');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (4, 'Funkcja void w C++ zwraca:', 'Nic', 'Zero', 'Null', 'Fałsz');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (4, 'W Pythonie, lista jest:', 'Mutowalna (zmienialna)', 'Niemutowalna', 'Stała', 'Statyczna');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (4, 'Co to jest "breakpoint"?', 'Punkt zatrzymania programu przy debugowaniu', 'Błąd krytyczny', 'Koniec pętli', 'Przerwa w dostępie do sieci');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (4, 'Ping służy do:', 'Sprawdzenia dostępności hosta w sieci', 'Pobierania strony www', 'Ataku na serwer', 'Szyfrowania danych');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (4, 'Pliki "cookies" są przechowywane:', 'W przeglądarce użytkownika', 'Na serwerze', 'W chmurze', 'W bazie danych SQL');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (5, 'Co to jest "klasa"?', 'Szablon do tworzenia obiektów', 'Zmienna globalna', 'Biblioteka systemowa', 'Funkcja matematyczna');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (5, 'Która struktura działa na zasadzie LIFO (Last In, First Out)?', 'Stos (Stack)', 'Kolejka (Queue)', 'Drzewo', 'Lista');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (5, 'Metoda "konstruktor" służy do:', 'Inicjalizacji obiektu', 'Usuwania obiektu', 'Kopiowania obiektu', 'Sortowania tablicy');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (5, 'W języku Java, każda instrukcja kończy się:', 'Średnikiem (;)', 'Kropką (.)', 'Dwukropkiem (:)', 'Przecinkiem (,)');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (5, 'Co oznacza DRY?', 'Don\'t Repeat Yourself', 'Do Repeat Yourself', 'Data Recovery Yield', 'Don\'t Remove Yarn');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (5, 'Framework React jest tworzony przez:', 'Facebook (Meta)', 'Google', 'Microsoft', 'Twitter');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (5, 'Co to jest "commit"?', 'Zatwierdzenie zmian w repozytorium', 'Pobranie zmian', 'Wysłanie zmian', 'Utworzenie gałęzi');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (5, 'Co oznacza skrót IoT?', 'Internet of Things', 'Input of Text', 'Internet of Technology', 'Internal operating Tool');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (5, 'Co robi polecenie "sudo"?', 'Wykonuje komendę jako administrator', 'Usuwa system', 'Aktualizuje system', 'Pobiera pliki');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (5, 'Język SQL jest językiem:', 'Deklaratywnym', 'Imperatywnym', 'Proceduralnym', 'Funkcyjnym');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (5, 'Wybierz język silnie typowany:', 'Java', 'JavaScript', 'Python', 'PHP');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (5, 'Stos (Stack) używa metod:', 'Push i Pop', 'Enqueue i Dequeue', 'Insert i Select', 'Add i Remove');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (5, 'Co oznacza RWD?', 'Responsive Web Design', 'Read Write Data', 'Remote Web Data', 'Real Web Development');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (5, 'Co to jest "overflow"?', 'Przekroczenie zakresu zmiennej', 'Przepełnienie dysku', 'Zbyt szybki internet', 'Błąd składni');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (6, 'Który typ danych jest najlepszy dla ceny?', 'Decimal', 'Float', 'Double', 'Integer');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (6, 'Co to jest "dziedziczenie"?', 'Przekazywanie cech z klasy nadrzędnej', 'Ukrywanie danych', 'Wielopostaciowość metod', 'Kopiowanie pamięci');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (6, 'W SQL, klauzula WHERE służy do:', 'Filtrowania rekordów', 'Sortowania rekordów', 'Grupowania rekordów', 'Łączenia tabel');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (6, 'Język skryptowy po stronie klienta to:', 'JavaScript', 'Java', 'C++', 'PHP');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (6, 'Co oznacza JSON?', 'JavaScript Object Notation', 'Java Source Object Network', 'JavaScript Online Notation', 'Java System Object Node');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (6, 'Który port jest domyślny dla HTTPS?', '443', '80', '21', '22');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (6, 'Słowo kluczowe "static" oznacza, że pole należy do:', 'Klasy, nie obiektu', 'Obiektu, nie klasy', 'Metody', 'Pakietu');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (6, 'Co to jest "refaktoryzacja"?', 'Zmiana struktury kodu bez zmiany zachowania', 'Naprawianie błędów', 'Dodawanie nowych funkcji', 'Formatowanie tekstu');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (6, 'DOM w przeglądarce to:', 'Document Object Model', 'Data Object Mode', 'Document Online Model', 'Disk Operating Method');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (6, 'Która baza jest bazą NoSQL?', 'MongoDB', 'PostgreSQL', 'MySQL', 'Oracle');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (6, 'Klasa abstrakcyjna:', 'Nie może mieć instancji', 'Musi być pusta', 'Jest zawsze statyczna', 'Nie ma metod');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (6, 'Interfejs w Javie zawiera:', 'Tylko sygnatury metod (przed Java 8)', 'Implementację metod', 'Zmienne instancyjne', 'Konstruktory');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (6, 'Wybierz system kontroli wersji:', 'Mercurial', 'Notepad', 'Excel', 'Slack');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (7, 'Złożoność O(n^2) jest typowa dla:', 'Sortowania bąbelkowego', 'Wyszukiwania binarnego', 'Dostępu do tablicy', 'Quick Sort (best case)');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (7, 'Co oznacza skrót HTTP?', 'HyperText Transfer Protocol', 'HyperText Transfer Program', 'High Transfer Text Protocol', 'Host Text Transfer Protocol');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (7, 'W modelu MVC, "V" oznacza:', 'View', 'Variable', 'Vector', 'Value');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (7, 'Co robi operacja JOIN w SQL?', 'Łączy dane z dwóch lub więcej tabel', 'Usuwa duplikaty', 'Tworzy nową tabelę', 'Dzieli kolumnę');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (7, 'Słowo kluczowe do obsługi wyjątków:', 'Try / Catch', 'If / Else', 'Do / While', 'Switch / Case');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (7, 'Normalizacja bazy danych ma na celu:', 'Redukcję redundancji danych', 'Zwiększenie rozmiaru bazy', 'Szybsze pisanie zapytań', 'Utworzenie kopii zapasowej');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (7, 'Scrum to metodologia typu:', 'Agile', 'Waterfall', 'V-Model', 'Spiral');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (7, 'Złożoność O(log n) jest:', 'Szybsza niż O(n)', 'Wolniejsza niż O(n)', 'Taka sama jak O(n)', 'Szybsza niż O(1)');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (7, 'Struktura "Graf" składa się z:', 'Wierzchołków i krawędzi', 'Komórek i wskaźników', 'Wierszy i kolumn', 'Kluczy i wartości');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (7, 'ORM mapuje:', 'Obiekty w kodzie na tabele w bazie', 'URL na pliki', 'Funkcje na zmienne', 'Porty na IP');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (7, 'DDoS to atak typu:', 'Distributed Denial of Service', 'Direct Data on Server', 'Domain Data over Socket', 'Double Disc on System');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (8, 'Czym różni się GIT od GitHuba?', 'GIT to narzędzie, GitHub to serwis', 'To to samo', 'GitHub to nowsza wersja GITa', 'GIT jest płatny');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (8, 'Protokół UDP różni się od TCP tym, że:', 'Nie gwarantuje dostarczenia pakietów', 'Jest wolniejszy', 'Jest używany tylko do e-maili', 'Wymaga połączenia');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (8, 'Co to jest "Primary Key"?', 'Unikalny identyfikator rekordu', 'Najważniejsza kolumna tekstowa', 'Klucz szyfrujący', 'Pierwsza kolumna w tabeli');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (8, 'Wzorzec Singleton gwarantuje:', 'Istnienie tylko jednej instancji klasy', 'Globalny dostęp do zmiennych', 'Bezpieczeństwo wielowątkowe', 'Szybkość działania');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (8, 'Co oznacza API?', 'Application Programming Interface', 'Application Protocol Interface', 'Advanced Programming Interaction', 'Automated Program Integration');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (8, 'Język asembler jest językiem:', 'Niskiego poziomu', 'Wysokiego poziomu', 'Skryptowym', 'Obiektowym');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (8, 'Szyfrowanie asymetryczne używa:', 'Klucza publicznego i prywatnego', 'Jednego klucza', 'Tylko hasła', 'Odcisku palca');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (8, 'Co to jest JWT?', 'JSON Web Token', 'Java Web Token', 'JavaScript Web Tool', 'JSON Web Tool');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (8, 'Co to jest "mock" w testach?', 'Obiekt udający prawdziwy obiekt', 'Błąd w teście', 'Rodzaj bazy danych', 'Narzędzie do kompilacji');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (8, 'Co to jest "daemon" w systemie Unix?', 'Proces działający w tle', 'Złośliwe oprogramowanie', 'Użytkownik root', 'Rodzaj pliku');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (9, 'Atak SQL Injection polega na:', 'Wstrzyknięciu kodu SQL w input', 'Przepełnieniu bufora', 'Przechwyceniu ciasteczek', 'Blokowaniu serwera (DDoS)');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (9, 'Co to jest polimorfizm?', 'Traktowanie różnych obiektów tak samo', 'Ukrywanie implementacji', 'Dziedziczenie wielokrotne', 'Automatyczne zarządzanie pamięcią');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (9, 'Wyszukiwanie binarne wymaga danych:', 'Posortowanych', 'Unikalnych', 'Liczbowych', 'W strukturze drzewa');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (9, 'Zasada "Open/Closed" mówi:', 'Otwarte na rozbudowę, zamknięte na modyfikację', 'Otwarte źródło, zamknięty kod', 'Otwarta baza, zamknięte połączenie', 'Otwarty dostęp, zamknięte dane');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (9, 'Garbage Collection zajmuje się:', 'Automatycznym zwalnianiem pamięci', 'Czyszczeniem bazy danych', 'Usuwaniem starych plików', 'Logowaniem błędów');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (9, 'Co to jest "big endian"?', 'Kolejność bajtów od najbardziej znaczącego', 'Duża baza danych', 'Końcówka pliku', 'Błąd kompilacji');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (9, 'Vulkan to:', 'Niskopoziomowe API graficzne', 'Język programowania', 'Baza danych', 'System operacyjny');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (9, 'Co oznacza SOLID (S)?', 'Single Responsibility Principle', 'Simple Responsibility Principle', 'Secure Object Language ID', 'System Object Level ID');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (10, 'Co to jest Deadlock?', 'Dwa procesy blokują się nawzajem', 'Błąd krytyczny procesora', 'Zakończenie programu', 'Wyciek pamięci');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (10, 'Co oznacza ACID?', 'Atomowość, Spójność, Izolacja, Trwałość', 'Autoryzacja, Czas, Identyfikacja, Dane', 'Asynchroniczność, Cache, Interfejs, Dostęp', 'Algorytm, Kod, Informacja, Dane');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (10, 'Do czego służy Docker?', 'Do konteneryzacji aplikacji', 'Do wirtualizacji systemu', 'Do zarządzania bazą danych', 'Do kompilacji kodu');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (10, 'Złożoność dostępu w Hash Mapie (średnio):', 'O(1)', 'O(n)', 'O(log n)', 'O(n^2)');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (10, 'Co to jest "Race Condition"?', 'Błąd niesynchronizowanego dostępu do danych', 'Wyścig procesorów', 'Szybkie wykonywanie pętli', 'Warunek zakończenia rekurencji');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (10, 'W architekturze Hexagonalnej kluczowe są:', 'Porty i Adaptery', 'Warstwy i Filtry', 'Okna i Widoki', 'Tabele i Relacje');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (11, 'Twierdzenie CAP mówi, że można spełnić max:', 'Dwa z trzech warunków', 'Wszystkie trzy warunki', 'Jeden warunek', 'Żadnego warunku');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (11, 'Co robi "Load Balancer"?', 'Rozdziela ruch na wiele serwerów', 'Zwiększa prędkość procesora', 'Kompresuje dane', 'Szyfruje połączenie');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (11, 'Wskaźnik (Pointer) w C++ przechowuje:', 'Adres w pamięci', 'Wartość zmiennej', 'Typ zmiennej', 'Rozmiar zmiennej');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (11, 'Mikroserwisy to:', 'Podział aplikacji na małe, niezależne usługi', 'Jeden wielki kod źródłowy', 'Wspólna baza dla wszystkich modułów', 'Brak komunikacji sieciowej');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (11, 'Co to jest "Blue-Green Deployment"?', 'Wdrażanie z dwoma identycznymi środowiskami', 'Błąd ekranu Windows', 'Rodzaj ataku hakerskiego', 'Wdrażanie tylko w nocy');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (12, 'Indeks B-Tree jest optymalizowany pod:', 'Operacje odczytu i zakresów', 'Tylko operacje zapisu', 'Dane tekstowe', 'Dane binarne');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (12, 'Idempotentność w REST API oznacza:', 'Wielokrotne wywołanie daje ten sam efekt', 'Każde wywołanie zmienia stan', 'Metoda jest asynchroniczna', 'Metoda wymaga autoryzacji');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (12, 'Problem "ABA" jest związany z:', 'Programowaniem wielowątkowym (CAS)', 'Normalizacją baz danych', 'Sortowaniem tablic', 'Kompilacją kodu JIT');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (12, 'W systemach Linux, "inode" przechowuje:', 'Metadane pliku, bez nazwy i treści', 'Tylko nazwę pliku', 'Treść pliku', 'Uprawnienia root');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (12, 'Co to jest "Memory Leak"?', 'Niezwolnienie pamięci po użyciu', 'Fizyczne uszkodzenie RAM', 'Błąd dysku twardego', 'Zbyt mała ilość RAM');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (1, 'Co oznacza skrót RAM?', 'Random Access Memory', 'Read Access Memory', 'Real Application Memory', 'Run Active Module');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (1, 'Który klawisz zwykle służy do odświeżenia strony w przeglądarce?', 'F5', 'F1', 'F12', 'Esc');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (1, '1 megabajt (MB) to:', '1024 kilobajty', '1000 bitów', '100 gigabajtów', '1024 bity');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (1, 'Rozszerzenie pliku .css dotyczy:', 'Arkuszy stylów', 'Skryptów C++', 'Bazy danych', 'Obrazków');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (1, 'Jaki jest wynik: 5 * 0?', '0', '5', '1', 'Null');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (2, 'Co oznacza symbol "&&" w wielu językach?', 'Logiczne ORAZ (AND)', 'Logiczne LUB (OR)', 'Przypisanie', 'Wskaźnik');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (2, 'Który tag HTML tworzy nagłówek największego stopnia?', '<h1>', '<h6>', '<head>', '<header>');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (2, 'Co to jest "URL"?', 'Adres internetowy zasobu', 'Język programowania', 'Rodzaj wirusa', 'Protokół pocztowy');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (2, 'Czym jest system operacyjny?', 'Oprogramowaniem zarządzającym komputerem', 'Przeglądarką internetową', 'Rodzajem klawiatury', 'Edytorem tekstu');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (2, 'Co oznacza skrót "www"?', 'World Wide Web', 'World Web Wide', 'Web Wide World', 'Wide World Web');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (2, 'Jaki kolor w systemie RGB to (255, 0, 0)?', 'Czerwony', 'Zielony', 'Niebieski', 'Czarny');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (2, 'Który z poniższych NIE jest językiem programowania?', 'HTML', 'Python', 'Java', 'C#');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (3, 'Jak w CSS zaznaczyć element po ID?', '#id', '.id', '*id', '$id');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (3, 'Co robi operator "++" (inkrementacja)?', 'Zwiększa wartość o 1', 'Zmniejsza wartość o 1', 'Mnoży razy 2', 'Dzieli przez 2');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (3, 'Co to jest "pętla nieskończona"?', 'Pętla, która nigdy się nie kończy', 'Pętla wykonana raz', 'Błąd kompilatora', 'Pętla z jedną instrukcją');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (3, 'Wartość logiczna "True" zamieniona na liczbę to zazwyczaj:', '1', '0', '-1', '10');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (3, 'Która funkcja w Pythonie wypisuje tekst na ekran?', 'print()', 'echo()', 'console.log()', 'System.out.println()');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (3, 'Tablica (Array) to struktura danych, która:', 'Przechowuje kolekcję elementów', 'Szyfruje dane', 'Łączy się z siecią', 'Wyświetla grafikę');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (4, 'Co oznacza słowo kluczowe "return"?', 'Zwraca wynik z funkcji', 'Powtarza pętlę', 'Zamyka program', 'Deklaruje zmienną');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (4, 'Co to jest "konkatenacja"?', 'Łączenie dwóch ciągów znaków (stringów)', 'Dzielenie liczb', 'Usuwanie spacji', 'Zamiana na wielkie litery');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (4, 'W SQL, aby dodać nowy rekord, używamy:', 'INSERT INTO', 'ADD NEW', 'UPDATE', 'CREATE ROW');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (4, 'Instrukcja "switch" jest alternatywą dla:', 'Wielu instrukcji IF', 'Pętli FOR', 'Deklaracji zmiennych', 'Funkcji rekurencyjnej');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (4, 'Zmienna typu "Boolean" może przyjąć wartości:', 'Prawda lub Fałsz', 'Dowolną liczbę', 'Tylko tekst', 'Pusty zbiór');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (4, 'Który znak kończy linię w C++, C# i Java?', ';', '.', ':', '!');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (5, 'Słowo kluczowe "this" (lub "self") odnosi się do:', 'Bieżącej instancji obiektu', 'Poprzedniej metody', 'Klasy nadrzędnej', 'Zmiennej globalnej');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (5, 'Metoda "Gettery" i "Settery" służą do:', 'Enkapsulacji (hermetyzacji) danych', 'Szybszego działania', 'Dziedziczenia klas', 'Obsługi błędów');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (5, 'Co oznacza skrót DNS?', 'Domain Name System', 'Data Network Service', 'Domain Network System', 'Digital Name Server');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (5, 'Framework Bootstrap służy głównie do:', 'Stylowania stron (CSS)', 'Zarządzania bazą danych', 'Pisania logiki backendu', 'Testowania aplikacji');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (5, 'Co to jest "bug report"?', 'Opis błędu zgłaszany przez użytkownika/testera', 'Raport finansowy', 'Kod źródłowy', 'Log serwera');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (5, 'W modelu klient-serwer, przeglądarka to:', 'Klient', 'Serwer', 'Baza danych', 'Router');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (6, 'Co oznacza "403 Forbidden"?', 'Brak uprawnień do zasobu', 'Zasób nie istnieje', 'Błąd serwera', 'Przekierowanie');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (6, 'Słowo kluczowe "extends" w Javie oznacza:', 'Dziedziczenie klasy', 'Implementację interfejsu', 'Utworzenie wyjątku', 'Import biblioteki');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (6, 'Typ danych "char" przechowuje:', 'Pojedynczy znak', 'Całe zdanie', 'Liczbę całkowitą', 'Datę');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (6, 'Co to jest "Responsive Design"?', 'Dostosowanie strony do różnych ekranów', 'Szybkie ładowanie strony', 'Design w odcieniach szarości', 'Animacje na stronie');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (6, 'Wiersz poleceń w Windows to:', 'cmd.exe', 'bash', 'finder', 'root');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (6, 'Format pliku graficznego obsługujący przezroczystość to:', 'PNG', 'JPG', 'BMP', 'TXT');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (6, 'Co robi komenda "git clone"?', 'Pobiera kopię repozytorium na dysk', 'Wysyła zmiany', 'Usuwa repozytorium', 'Tworzy nową gałąź');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (7, 'Co to jest "Unit Test"?', 'Test jednostkowy sprawdzający mały fragment kodu', 'Test całego systemu', 'Test wydajności', 'Test bezpieczeństwa');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (7, 'Co oznacza akronim MVP w biznesie IT?', 'Minimum Viable Product', 'Most Valuable Programmer', 'Maximum Virtual Power', 'Model View Presenter');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (7, 'Metoda HTTP POST służy zazwyczaj do:', 'Wysyłania danych na serwer', 'Pobierania danych', 'Usuwania danych', 'Pobierania nagłówków');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (7, 'Co to jest "klucz obcy" (Foreign Key)?', 'Pole łączące dwie tabele w bazie', 'Hasło administratora', 'Unikalny klucz główny', 'Klucz do szyfrowania');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (7, 'Agile to podejście do wytwarzania oprogramowania, które jest:', 'Zwinne i iteracyjne', 'Sztywne i linearne', 'Tylko dla małych firm', 'Oparte na braku dokumentacji');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (8, 'W systemie Linux, polecenie "chmod 777" oznacza:', 'Pełne prawa dla właściciela, grupy i innych', 'Brak praw dla nikogo', 'Tylko odczyt dla wszystkich', 'Usunięcie pliku');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (7, 'Co oznacza skrót MVC?', 'Model View Controller', 'Model View Class', 'Main Virtual Controller', 'Make View Code');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (6, 'W języku C++, destruktor nazywa się tak samo jak klasa, ale z prefixem:', '~ (tylda)', '#', '!', '-');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (8, 'Co to jest "hoisting" w JavaScript?', 'Przenoszenie deklaracji zmiennych/funkcji na górę zakresu', 'Usuwanie zmiennych', 'Kompresja kodu', 'Sortowanie tablicy');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (3, 'Jaki jest wynik logiczny: NOT (True OR False)?', 'False', 'True', 'Null', 'Undefined');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (5, 'Co to jest "foreign key" (klucz obcy)?', 'Pole wskazujące na klucz główny w innej tabeli', 'Unikalny klucz tabeli', 'Hasło do bazy', 'Błąd połączenia');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (4, 'W Pythonie, słownik (dict) przechowuje dane jako:', 'Pary klucz-wartość', 'Lista indeksowana liczbami', 'Tylko wartości', 'Drzewo binarne');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (4, 'Protokół FTP służy do:', 'Przesyłania plików', 'Wysyłania maili', 'Wyświetlania stron www', 'Synchronizacji czasu');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (6, 'Co oznacza "agile" w zarządzaniu projektami?', 'Zwinne podejście, nastawione na zmiany', 'Sztywne planowanie na lata', 'Brak dokumentacji', 'Praca bez managera');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (5, 'Funkcja agregująca w SQL licząca wiersze to:', 'COUNT()', 'SUM()', 'AVG()', 'MAX()');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (6, 'W CSS, właściwość "z-index" odpowiada za:', 'Kolejność wyświetlania elementów na osi Z (warstwy)', 'Przezroczystość', 'Rozmiar czcionki', 'Kolor tła');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (5, 'Co to jest "cache"?', 'Pamięć podręczna do szybkiego dostępu', 'Kosz na śmieci', 'Baza danych użytkowników', 'Procesor graficzny');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (5, 'W Javie słowo "final" przy zmiennej oznacza:', 'Że jej wartość nie może zostać zmieniona (stała)', 'Że to ostatnia zmienna w kodzie', 'Że zmienna jest prywatna', 'Że zmienna jest usuwana');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (7, 'Jaki port obsługuje protokół SMTP (poczta)?', '25', '80', '443', '21');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (2, 'Co to jest "syntax error"?', 'Błąd składniowy (źle napisany kod)', 'Błąd logiczny', 'Błąd dysku', 'Błąd sieci');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (6, 'Framework Laravel jest napisany w:', 'PHP', 'Python', 'Java', 'Ruby');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (3, 'Co to jest "open source"?', 'Oprogramowanie z dostępnym kodem źródłowym', 'Oprogramowanie płatne', 'Oprogramowanie tylko dla firm', 'Wirus komputerowy');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (2, 'Kto jest założycielem firmy Microsoft?', 'Bill Gates', 'Steve Jobs', 'Elon Musk', 'Mark Zuckerberg');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (3, 'Co oznacza skrót SSD?', 'Solid State Drive', 'Super Speed Disk', 'System Storage Device', 'Slow State Drive');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (4, 'Wybierz język znaczników:', 'XML', 'Python', 'C++', 'Java');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (9, 'Algorytm Dijkstry służy do:', 'Znajdowania najkrótszej ścieżki w grafie', 'Sortowania liczb', 'Szyfrowania danych', 'Kompresji obrazu');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (3, 'Co to jest "cookie"?', 'Mały plik tekstowy zapisywany przez przeglądarkę', 'Rodzaj procesora', 'Program antywirusowy', 'Błąd w Javie');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (9, 'Wykrywanie kolizji w Hash Mapie można rozwiązać przez:', 'Chaining (łańcuchowanie)', 'Usunięcie danych', 'Restart serwera', 'Zwiększenie RAM');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (7, 'Co to jest "kernel"?', 'Jądro systemu operacyjnego', 'Obudowa komputera', 'Główny procesor', 'Rodzaj klawiatury');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (2, 'W HTML, tag <a> służy do:', 'Tworzenia linków (hiperłączy)', 'Pogrubienia tekstu', 'Wstawiania obrazka', 'Tworzenia tabeli');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (5, 'Język Swift jest głównie używany do tworzenia aplikacji na:', 'iOS / macOS', 'Android', 'Windows', 'Linux');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (8, 'Złożoność obliczeniowa O(1) oznacza czas:', 'Stały', 'Liniowy', 'Wykładniczy', 'Logarytmiczny');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (4, 'W SQL polecenie DELETE służy do:', 'Usuwania rekordów', 'Usuwania całej tabeli', 'Usuwania bazy danych', 'Aktualizacji danych');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (5, 'Co to jest "backend"?', 'Część serwerowa aplikacji (logika, baza danych)', 'Wygląd strony', 'Przeglądarka internetowa', 'Monitor użytkownika');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (7, 'Co robi metoda ".map()" w JavaScript na tablicy?', 'Tworzy nową tablicę z wynikami funkcji dla każdego elementu', 'Usuwa elementy', 'Sortuje tablicę', 'Filtruje tablicę');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (3, 'Co oznacza skrót GUI?', 'Graphical User Interface', 'Global User Input', 'General Unit Interface', 'Graphic Unit Input');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (8, 'Wzorzec "Factory" (Fabryka) służy do:', 'Tworzenia obiektów bez określania dokładnej klasy', 'Niszczenia obiektów', 'Łączenia baz danych', 'Testowania kodu');
INSERT INTO mil.questions (level, quest, ans, bad1, bad2, bad3) VALUES (4, 'Zasada KISS w programowaniu oznacza:', 'Keep It Simple, Stupid', 'Keep It Safe, Secure', 'Kernel Input System Service', 'Key Index Storage System');
