var searchData=
[
  ['faculty_20of_20automatic_20control_20robotics_20and_20computer_20science_20on_20silesian_20university_20of_20technology_0',['Project for first semester of Informatics on faculty of Automatic control, Robotics and Computer Science on Silesian University of Technology',['../md_readme.html#autotoc_md1',1,'']]],
  ['file_1',['Content of the database/.env file',['../md_readme.html#autotoc_md8',1,'']]],
  ['file_20and_20database_20sql_20files_2',['It generates automatically schema, tables and inserts questions, u can change it in database/dbInit.cpp file and database/*.sql files',['../md_readme.html#autotoc_md10',1,'']]],
  ['file_20is_20database_20dbquerys_20cpp_3',['This app has one file that executes mysql querys, this file is database/dbQuerys.cpp',['../md_readme.html#autotoc_md11',1,'']]],
  ['file_20s_20tree_20of_20compiled_20game_3a_4',['Proper file&apos;s tree of compiled game:',['../md_readme.html#autotoc_md6',1,'']]],
  ['file_20that_20executes_20mysql_20querys_20this_20file_20is_20database_20dbquerys_20cpp_5',['This app has one file that executes mysql querys, this file is database/dbQuerys.cpp',['../md_readme.html#autotoc_md11',1,'']]],
  ['files_6',['It generates automatically schema, tables and inserts questions, u can change it in database/dbInit.cpp file and database/*.sql files',['../md_readme.html#autotoc_md10',1,'']]],
  ['first_20semester_20of_20informatics_20on_20faculty_20of_20automatic_20control_20robotics_20and_20computer_20science_20on_20silesian_20university_20of_20technology_7',['Project for first semester of Informatics on faculty of Automatic control, Robotics and Computer Science on Silesian University of Technology',['../md_readme.html#autotoc_md1',1,'']]],
  ['following_20e_20mail_20address_3a_20hannapotepa_20com_8',['For contact regarding this game please use following e-mail address: &lt;a href=&quot;#&quot; onclick=&quot;location.href=&apos;mai&apos;+&apos;lto:&apos;+&apos;han&apos;+&apos;na&apos;+&apos;pot&apos;+&apos;ep&apos;+&apos;a@i&apos;+&apos;cl&apos;+&apos;oud&apos;+&apos;.c&apos;+&apos;om&apos;; return false;&quot;&gt;hannapotepa@icloud.com&lt;/a&gt;',['../md_readme.html#autotoc_md3',1,'']]],
  ['for_20commercial_20use_9',['Project made for learning purposes, not for commercial use.',['../md_readme.html#autotoc_md2',1,'']]],
  ['for_20contact_20regarding_20this_20game_20please_20use_20following_20e_20mail_20address_3a_20hannapotepa_20com_10',['For contact regarding this game please use following e-mail address: &lt;a href=&quot;#&quot; onclick=&quot;location.href=&apos;mai&apos;+&apos;lto:&apos;+&apos;han&apos;+&apos;na&apos;+&apos;pot&apos;+&apos;ep&apos;+&apos;a@i&apos;+&apos;cl&apos;+&apos;oud&apos;+&apos;.c&apos;+&apos;om&apos;; return false;&quot;&gt;hannapotepa@icloud.com&lt;/a&gt;',['../md_readme.html#autotoc_md3',1,'']]],
  ['for_20first_20semester_20of_20informatics_20on_20faculty_20of_20automatic_20control_20robotics_20and_20computer_20science_20on_20silesian_20university_20of_20technology_11',['Project for first semester of Informatics on faculty of Automatic control, Robotics and Computer Science on Silesian University of Technology',['../md_readme.html#autotoc_md1',1,'']]],
  ['for_20learning_20purposes_20not_20for_20commercial_20use_12',['Project made for learning purposes, not for commercial use.',['../md_readme.html#autotoc_md2',1,'']]],
  ['formating_2eh_13',['formating.h',['../formating_8h.html',1,'']]]
];
